region_1: ""
region_2: ""
ansible_collection_tag: "main"
ansible_collection_url: "git+https://github.com/ddevadat/iac-devops.git#/ansible/istio/iac"
home_region: ""
tenancy_id: ""
compartment_id: ""
ad_count: 1
namespace: ""