- name: Upload troubleshooting app deploy scripts 
  template:
    src: "deploy_troubleshooting.sh.j2"
    dest: "{{scripts_location}}/deploy_troubleshooting.sh"
    mode: "0700"


- name: Execute trouble app deploy scripts
  ansible.builtin.shell: "{{scripts_location}}/deploy_troubleshooting.sh > deploy_troubleshooting.log"
  args:
    chdir: "{{scripts_location}}/"
    creates: deploy_troubleshooting.log
