- name: Uninstall istio
  shell: |
    export KUBECONFIG="/root/.kube/config"
    export CTX_CLUSTER1=oke_cluster1
    export CTX_CLUSTER2=oke_cluster2
    export PATH="/root/istio-{{istio_version}}/bin:$PATH"
    istioctl uninstall --context="${CTX_CLUSTER1}" -y --purge
    istioctl uninstall --context="${CTX_CLUSTER2}" -y --purge


